name: Release GitHub Pages

runs:
  using: 'node20'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout released code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Stamp release version
      run: VERSION=${{github.event.release.tag_name}} npm run stamp-version
    - name: Perform production build
      run: npm run build
    - name: Deploy build to GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: build
